export const headers = [
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: "WidgetId",
    accessor: "WidgetId",
    style: {},
  },
  {
    width: 110,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: "WidgetType",
    accessor: "WidgetType",
    style: {},
  },
  {
    width: 110,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: "Name",
    accessor: "Name",
    style: {},
  },
  {
    width: 150,
    sortable: true,
    resizable: true,
    filterable: false,
    minWidth: 100,
    minResizeWidth: 100,
    show: true,
    id: "CreationDate",
    style: {},
  },
  {
    Header: "",
    id: "grid-actions",
    sortable: false,
    resizable: false,
  },
];
export const data = [
  {
    Id: 3228,
    WidgetId: "3228",
    Name: "schilling_dashboard_demo",
    WidgetType: 2,
    DataSource:
      '{"View":"VwDebtorTransactionsV01","Description":"schilling_dashboard_demo","Function":"Sum","CategorizeBy":"CustomerNumber","AggBy":"CustomerTransactionAmount","SortBy":{"id":"CustomerNumber","desc":false}}',
    FilterId: 259,
    DefaultOptions:
      '{"Theme":"blue","BarFill":"solid","ScalingFunction":"sqrt"}',
    IsDefault: 0,
    CreationUser: 500,
    CreationDate: "2024-07-01T13:28:34+02:00",
    ModificationUser: 500,
    ModificationDate: "2024-07-01T13:28:34+02:00",
  },
  {
    Id: 3227,
    WidgetId: "3227",
    Name: "progress",
    WidgetType: 7,
    DataSource:
      '{"View":"VwDebtorTransactionsV01","Description":"progress test","Filter2":259}',
    FilterId: 1785,
    DefaultOptions: '{"Theme":"green"}',
    IsDefault: 0,
    CreationUser: 500,
    CreationDate: "2024-06-18T13:42:49+02:00",
    ModificationUser: 500,
    ModificationDate: "2024-06-18T13:42:49+02:00",
  },
  {
    Id: 3226,
    WidgetId: "3226",
    Name: "martins egen widget",
    WidgetType: 2,
    DataSource:
      '{"View":"VwRightsSalesAggrV01","Description":"martins egen widget","Function":"Sum","CategorizeBy":"Year","AggBy":"TotalIncome","SortBy":{"id":"Year","desc":false}}',
    FilterId: 1794,
    DefaultOptions:
      '{"Theme":"red","BarFill":"solid","ScalingFunction":"sqrt"}',
    IsDefault: 0,
    CreationUser: 500,
    CreationDate: "2024-06-18T13:39:20+02:00",
    ModificationUser: 500,
    ModificationDate: "2024-06-18T13:39:20+02:00",
  },
  {
    Id: 3225,
    WidgetId: "3225",
    Name: "min fine widget med ukendt tæller og nævner",
    WidgetType: 7,
    DataSource:
      '{"View":"VwRAgentAgreementV01","Description":"min fine widget med ukendt tæller og nævner2","Filter2":244}',
    FilterId: 59,
    DefaultOptions: '{"Theme":"blue"}',
    IsDefault: 0,
    CreationUser: 500,
    CreationDate: "2024-06-12T11:49:31+02:00",
    ModificationUser: 500,
    ModificationDate: "2024-06-12T11:49:31+02:00",
  },

];
export const config = {
  tableClass: "grid-table",
  tableStyle: {
    maxHeight: "117px",
  },

  manual: true,
  page: 0,
  pageSize: 20,
  pages: 6,
  rows: 102,
  loading: false,
  sortBy: [
    {
      id: "CreationDate",
      desc: true,
    },
  ],
  defaultPageSize: 20,
  pageSizeOptions: [20, 50, 100],
  sortable: true,
  exportable: false,
  filterable: true,
  orderable: false,
  excludable: false,
  configurable: false,
  filters: {
    ColSearch: {},
    AdvSearch: {},
    GrpSearch: {},
  },
  activeFilter: null,
  filterMeta: [
    {
      AdditionalKeys: [],
      Description: "Internal widget ID",
      HasLookup: false,
      Name: "Id",
      Type: 1,
      Domain: 3480,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Widget ID",
      HasLookup: false,
      Name: "WidgetId",
      Type: 0,
      Domain: 3481,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Widget name",
      HasLookup: false,
      Name: "Name",
      Type: 0,
      Domain: 3482,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Widget type",
      HasLookup: false,
      Name: "WidgetType",
      Type: 1,
      Domain: 3483,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Data source",
      HasLookup: false,
      Name: "DataSource",
      Type: 0,
      Domain: 3484,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Filter ID",
      HasLookup: false,
      Name: "FilterId",
      Type: 1,
      Domain: 3487,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Default settings",
      HasLookup: false,
      Name: "DefaultOptions",
      Type: 0,
      Domain: 3485,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Default on dashboard",
      HasLookup: false,
      Name: "IsDefault",
      Type: 1,
      Domain: 3486,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Created by",
      HasLookup: false,
      Name: "CreationUser",
      Type: 1,
      Domain: 3143,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Created",
      HasLookup: false,
      Name: "CreationDate",
      Type: 4,
      Domain: 3341,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Changed by",
      HasLookup: false,
      Name: "ModificationUser",
      Type: 1,
      Domain: 3144,
      Derived: false,
    },
    {
      AdditionalKeys: [],
      Description: "Changed",
      HasLookup: false,
      Name: "ModificationDate",
      Type: 4,
      Domain: 3193,
      Derived: false,
    },
  ],
  filterKey: "widgets/overview",
  selected: {
    View: "Widget",
    tableAPI: "schilling/webservice/Widget",
  },
  columnOrder: [
    "WidgetId",
    "WidgetType",
    "Name",
    "CreationUser",
    "CreationDate",
    "TrgId",
    "TrgType",
    "TrgCreationDate",
    "TrgIpAddress",
    "TrgOSUser",
    "TrgCurrentUser",
    "TrgExternalName",
    "TrgModule",
    "TrgSID",
    "Id",
    "DataSource",
    "FilterId",
    "DefaultOptions",
    "IsDefault",
    "ModificationUser",
    "ModificationDate",
  ],
  hiddenColumns: [
    "TrgId",
    "TrgType",
    "TrgCreationDate",
    "TrgIpAddress",
    "TrgOSUser",
    "TrgCurrentUser",
    "TrgExternalName",
    "TrgModule",
    "TrgSID",
    "Id",
    "CreationUser",
    "DataSource",
    "FilterId",
    "DefaultOptions",
    "IsDefault",
    "ModificationUser",
    "ModificationDate",
  ],
  i18n: {
    options: {
      debug: false,
      initImmediate: true,
      ns: ["translations"],
      defaultNS: "translations",
      fallbackLng: ["en"],
      fallbackNS: false,
      supportedLngs: false,
      nonExplicitSupportedLngs: false,
      load: "languageOnly",
      preload: false,
      simplifyPluralSuffix: true,
      keySeparator: ".",
      nsSeparator: ":",
      pluralSeparator: "_",
      contextSeparator: "_",
      partialBundledLanguages: false,
      saveMissing: false,
      updateMissing: false,
      saveMissingTo: "fallback",
      saveMissingPlurals: true,
      missingKeyHandler: false,
      missingInterpolationHandler: false,
      postProcess: false,
      postProcessPassResolved: false,
      returnNull: false,
      returnEmptyString: true,
      returnObjects: false,
      joinArrays: false,
      returnedObjectHandler: false,
      parseMissingKeyHandler: false,
      appendNamespaceToMissingKey: false,
      appendNamespaceToCIMode: false,
      interpolation: {
        escapeValue: false,
        prefix: "{{",
        suffix: "}}",
        formatSeparator: ",",
        unescapePrefix: "-",
        nestingPrefix: "$t(",
        nestingSuffix: ")",
        nestingOptionsSeparator: ",",
        maxReplaces: 1000,
        skipOnVariables: true,
      },
      detection: {
        order: [
          "localStorage",
          "navigator",
          "cookie",
          "querystring",
          "htmlTag",
          "path",
          "subdomain",
        ],
        lookupLocalStorage: "x-schilling-language",
        lookupQuerystring: "lng",
        lookupCookie: "i18next",
        lookupSessionStorage: "i18nextLng",
        caches: ["localStorage"],
        excludeCacheFor: ["cimode"],
      },
      whitelist: ["en", "da", "sv", "se", "no", "nb", "nn"],
      nonExplicitWhitelist: true,
      react: {
        useSuspense: true,
      },
      ignoreJSONStructure: true,
    },
    store: {
      en: {
        translations: {
          "2fa_must_be_filled": "Fill in the verification code",
          "2fa_not_setup": "Two-factor verification is not set up for the user",
          Configuration: "Configuration",
          Costs: "Costs",
          Count: "Count",
          CustomerName: "Customer",
          Date: "Date",
          Department: "Department",
          Employee: "Employee",
          Favorites: "Favourites",
          FormatList: "Format",
          FormatType: "Format type",
          From: "From",
          LangList: "Language",
          Menu: "Menu",
          NoGrouping: "No grouping",
          NotGrouped: "Not grouped",
          "Product(s)": "Product(s)",
          Projekt: "Project",
          "Recent Items": "Recent",
          Recipients: "Recipients",
          Reset_to_default: "Reset to default",
          RightsGenre: "Genre",
          RightsOriginatorsNames: "Author(s)",
          Run: "Run",
          Sales: "Sales",
          "Supplier Invoice Approval": "Supplier Invoice Approval",
          TerrList: "Territory",
          TrgCreationDate: "Created",
          TrgCurrentUser: "Current user",
          TrgExternalName: "External name",
          TrgId: "ID",
          TrgIpAddress: "IP address",
          TrgModule: "Module",
          TrgOSUser: "OS user name",
          TrgSID: "Database SID",
          TrgType: "Type",
          WorkDescription: "Title",
          a_database_error_occured: "A database error occured",
          absolute_value: "Absolute value",
          access_given_at_system_level: "Access given at system level",
          access_is_given_at: "Access is given at",
          account: "Account",
          accounted_vat: "Accounted VAT",
          accounting_codes: "Accounting codes",
          accounts: "Accounts",
          accrual_date: "Accrual date",
          accrual_key: "Accrual key",
          active: "Active",
          active_substitute: "Active substitute",
          activity: "Activity",
          actual_costs: "Actual costs",
          actual_end: "Actual end",
          actual_start: "Actual start",
          add: "Add",
          add_approver: "Add approver",
          add_approver_not_allowed_now: "'Add approver' not allowed now.",
          add_column: "Add column",
          add_comment: "Add comment",
          add_comment_for: "Add comment for {{approver}}",
          add_cost_type: "Add cost type",
          add_costs: "Add costs",
          add_criteria: "Add criteria",
          add_entry: "Add voucher line",
          add_filter: "Add filter",
          add_group: "Add group",
          add_notification: "Add notification",
          add_or_remove_widget: "Add or remove widget",
          add_product: "Add product",
          add_rate: "Add rate",
          add_recipient: "Add recipient",
          add_recipients: "Add recipients",
          add_return_date: "Add return date",
          add_rights_for_single_user_or_group:
            "Add rights for single user or group",
          add_substitute: "Add substitute",
          add_template: "Add template",
          add_to_favorites: "Add to favourites",
          add_user: "Add user",
          add_widget: "Add widget",
          additional_approvers_cannot_be_linked_to_this_voucher:
            "Additional approvers cannot be linked to this voucher.",
          administration_panel: "Administration panel",
          advanced: "Advanced",
          advanced_ladder_system_for_shares:
            "Advanced ladder system for shares",
          after: "After",
          agent_id: "Agent ID",
          agent_settlement: "Agent settlement",
          agg_by: "Aggregate by",
          agreement: "Agreement",
          agreement_creation_failed: "Agreement could not be created",
          agreement_id: "Agreement ID",
          agreement_name: "Agreement name",
          agreement_number: "Agreement number",
          agreement_recipient_type: "Agreement recipient type",
          agreement_status: "Agreement status",
          agreement_successfully_created: "Agreement successfully created",
          agreement_successfully_updated:
            'Update completed for agreement "{{name}}"',
          agreement_update_failed: "Agreement update failed",
          agreements: "Agreements",
          agreements_ready_for_settlement: "Agreements ready for settlement",
          agreements_ready_for_settlment: "Agreements ready for settlment",
          agreements_recipient_final_settlement:
            "Agreements/recipient, final settlement",
          agreements_transactions: "Agreements transactions",
          all: "All",
          all_companies: "All companies",
          all_media_types: "All media types",
          all_media_types_are_included: "All media types are included",
          all_overdue_vouchers: "All overdue vouchers",
          all_steps_completed: "All steps completed",
          all_users_and_groups: "All users and groups",
          all_users_and_groups_have_permission:
            "All users and groups have permission",
          all_vouchers_pending_processing: "All vouchers pending processing",
          amount: "Amount",
          amount_excluding_vat: "Amount excluding VAT",
          amount_including_vat: "Amount including VAT",
          and: "And",
          annually: "Annually",
          apartment_floor: "Apartment floor",
          apply_changes: "Apply changes",
          apply_filter: "Apply",
          approval_note_optional: "Approval note (optional)",
          approval_timeline: "Approval timeline",
          approve: "Approve",
          approve_all: "Approve for all",
          approve_for_me_and_subs: "Approve for me, {{subs}}",
          approve_for_substitutees: "Approve for {{subs}}",
          approve_present: "Approve",
          approved: "Approved",
          approved_blocked: "Approved (blocked)",
          approved_by: "Approved by",
          approved_by_all: "Approved by all",
          approver: "Approver",
          approver_is_a_required_field: "Approver is a required field",
          approver_is_already_linked_to_this_voucher:
            "Approver is already linked to this voucher.",
          approver_substitute: "Approver/substitute",
          approvers: "Approvers",
          approving: "Approving",
          are_you_sure_you_want_to_discard_the_changes:
            "Are you sure you want to discard the changes?",
          ascending: "Ascending",
          assign: "Assign",
          assign_packages: "Assign packages",
          assigned_packages: "Assigned packages",
          attach_files: "Attach files",
          "author(s)": "Author(s)",
          author_portal_already_configured: "Author portal already configured",
          author_portal_setup: "Author portal setup",
          author_portal_setup_cannot_be_verified:
            "Author portal setup cannot be verified",
          availability: "Availability",
          available: "Available",
          available_columns: "Available columns",
          available_packages_for_assignment:
            "Available packages for assignment",
          aww_dont_cry: "Oh no! Something went wrong!",
          back: "Back",
          back_to_vouchers: "Back to vouchers",
          balance: "Balance",
          bank_account_number: "Bank account number",
          bar_chart: "Bar chart",
          bcc_address: "Bcc address",
          before: "Before",
          between_recipients: "Between recipients",
          biannually: "Biannually",
          binding_code: "Binding code",
          blocked: "Blocked",
          browse_files: "Browse files",
          by: "By",
          calculated_costs: "Calculated costs",
          cancel: "Cancel",
          cancel_reset: "Cancel reset",
          categorize_by: "Categorise by",
          change: "Change",
          change_own_password: "Change own password",
          change_password_for_other_user: "Change password for other user",
          changes_saved: "Changes saved",
          choice: "Choice",
          choose_chart_settings: "Select chart settings",
          choose_column_to_search: "Select column",
          choose_view_to_search: "Select view",
          circulation: "Circulation",
          clear: "Clear",
          clear_all: "Clear all",
          click_here_to_view: "Click here to view",
          click_link_to_report_error: "Click on link to report error",
          click_to_remove: "Click to remove",
          click_to_report_error: "Click to report error",
          client_install_text:
            "We were not able to detect a Schilling Client installation.\nThe Schilling client is necessary for running Schilling applications.\n\nWould you like to download and install the latest version?",
          close: "Close",
          close_and_return_to_table: "Close and return to table",
          close_config: "Close configuration",
          color_theme: "Colour theme",
          column: "Column",
          column_order: "Column order",
          column_to_group_by: "Group by column",
          coming_publications: "Coming publications",
          comment: "Comment",
          companies: "Companies",
          company: "Company",
          companyname: "Company name",
          component_encountered_an_error: "Component encountered an error",
          config_grid: "Configure grid",
          confirm: "Confirm",
          confirm_reset_table_config: "Confirm reset table configuration",
          confirm_update_of_voucher_to:
            "Confirm update of voucher {{voucher}} to {{action}}",
          connection_error: "Connection error - please try again later",
          contains: "Contains",
          context: "Context",
          continue_as: "Continue as",
          costs: "Costs",
          count: "Count",
          countMore: "{{count}} more",
          countMore_plural: "{{count}} more",
          country: "Country",
          create: "Create",
          create_another: "Create another",
          create_chart: "Create chart",
          create_chart_from_saved_search: "Create chart from saved search",
          create_profit_sharing_agreement: "Create profit sharing agreement",
          create_schilling_package: "Create schilling package",
          create_settlement_run: "Create settlement run",
          create_support_issue: "Create support issue",
          create_widget: "Create widget",
          created: "Created",
          created_by: "Created by",
          creation_date: "Created",
          creditor: "Creditor",
          "creditor-address-information": "Creditor-address-information",
          "creditor-bank-details": "Creditor-bank-details",
          "creditor-personal-details": "Creditor-personal-details",
          creditor_as: "Show creditor as",
          creditor_name: "Creditor name",
          creditor_no: "Creditor number",
          criteria: "Criteria",
          criterias: "Criteria",
          currency: "Currency",
          currency_amount: "Currency amount",
          current_name: "Current name",
          current_publications: "Current publications",
          customer: "Customer",
          customer_package: "Customer package",
          dashboard: "Dashboard",
          dashboard_administration: "Dashboard administration",
          dashboard_is_now_in_configuration_mode:
            "Dashboard is now in configuration mode",
          data_overview: "Data Overview",
          date: "Date",
          date_as: "Show date as",
          date_must_be_after_the_latest_publication_date:
            "Date must be after the latest publication date",
          date_not_before_settlement_date:
            "Payment date may not be before the settlement date",
          days: "days",
          days_pending_approval: "Number of days pending approval",
          debtor: "Debtor",
          default_listsize: "Default list size",
          default_package: "Default package",
          default_package_name: "Default package name",
          delete: "Delete",
          delete_rows: "Delete rows",
          delimitation: "Delimitation",
          department: "Department",
          descending: "Descending",
          description: "Description",
          different_than: "Different from",
          dimensions: "Dimensions",
          distribute_share_evenly: "Distribute share evenly",
          do_you_want_to_discard_the_changes:
            "Do you want to discard the changes?",
          document: "Document",
          documentWithCount: "{{count}} document",
          documentWithCount_plural: "{{count}} documents",
          document_could_not_be_shown_since_fileformat_is_unsupported_or_file_is_corrupted:
            "Document could not be shown because file format is unsupported or file is corrupted.",
          document_management: "Document management",
          document_plural: "documents",
          does_not_contain: "Does not contain",
          download: "Download",
          download_description_text:
            "The new Schilling Client is a cross-platform client that enables you to work with all Schilling programs in any operating system. The new Schilling Client is required to open desktop applications from Schilling Access Point. Download the latest version of the new Schilling Client for Windows, Mac, or Linux here.",
          download_for: "Download for {{os}}",
          download_schilling_qtclient_for_desktop:
            "Download the new Schilling Client for desktop",
          downloading: "Downloading",
          downloads: "Downloads",
          drag_and_drop_columns_to_reorder:
            "Drag and drop columns to change order",
          due_date: "Due date",
          edit: "Edit",
          edit_profit_sharing_agreement: "Edit profit sharing agreement",
          edit_queue: "Edit queue",
          edit_recipient: "Edit recipient",
          edit_schilling_package: "Edit schilling package",
          edit_voucher: "Edit entry lines",
          editing_permissions_on_this_item_will_also_alter_the_permissions_on_rest_apis:
            "If you edit permissions on this item, permissions will also change on {{count}} REST API",
          editing_permissions_on_this_item_will_also_alter_the_permissions_on_rest_apis_plural:
            "If you edit permissions on this item, permissions will also change on {{count}} REST APIs",
          edition: "Edition",
          email: "E-mail",
          email_templates: "Email templates",
          employee: "Employee",
          empty_value: "(Blanks)",
          enable_all: "Enable all",
          end_date: "End date",
          enter_recipients_total_share: "Enter recipients' total share",
          enter_widget_description: "Enter widget description",
          enter_widget_info: "Enter widget information",
          enter_widget_name: "Enter widget name",
          entitites: "Entitites",
          entry_line: "Entry line",
          entry_lines: "Voucher lines",
          entry_not_allowed_now: "Entry not allowed now",
          entry_total: "Entry total",
          entry_type: "Select entry type",
          entry_type_is_a_required_field: "Entry type is a required field",
          environment: "Environment",
          equal_to: "Equal to",
          equals: "Equals",
          error: "Error",
          error_dialog_header: "Error dialog header",
          error_message_missing: "Error message missing",
          error_occured_in_schilling_workspace: "An error occurred",
          error_report: "Error report",
          everyone: "Everyone",
          exp_publication_date: "Expected publication date",
          expected_end: "Expected end",
          expected_start: "Expected start",
          export: "Export",
          extracted: "Extracted",
          faq: "FAQ",
          favorites: "Favourites",
          file_could_not_be_found: "File could not be found.",
          file_location: "File location",
          filter: "Filter",
          filter2: "Filter2",
          filter_by: "Filter by",
          filter_by_customer: "Filter by customer",
          filter_details: "Filter details",
          filter_items: "Filter items",
          finance: "Finance",
          financial_account: "Financial account",
          financial_account_is_a_required_field:
            "Financial account is a required field.",
          firstname: "First name",
          for_all_companies: "For all companies",
          for_distribution: "For distribution",
          for_publisher: "for publisher",
          foreign_extracted: "Foreign extracted",
          format_type: "Format type",
          formats: "Formats",
          free_text_search: "Free text search",
          from: "From",
          from_and_including: "From and including",
          from_date: "From",
          from_duedate: "From due date",
          from_user: "From user",
          function: "Function",
          general_downloads: "General downloads",
          generate_old_settlement_reports: "Generate old settlement reports",
          generate_posted_settlements: "Generate posted settlements",
          generate_preliminary_settlements_and_sales_figures:
            "Generate preliminary settlements and sales figures",
          generate_summary_page: "Generate summary page",
          genre: "Genre",
          get_started: "Get started",
          give_rights_to_all_users_and_groups:
            "Give rights to all users and groups",
          go_back: "Go back",
          go_back_to_dashboard: "Go back to dashboard",
          go_to_download_page: "Go to download page",
          go_to_global_search: "Go to global search",
          gradient: "Gradient",
          graph: "Graph",
          greater: "Greater",
          greater_than: "Greater than",
          greater_than_or_equal_to: "Greater than or equal to",
          group: "Group",
          group_by: "Group by",
          group_results_by_column: "Group results by column",
          group_smaller_slices_into_one_if_big_dataset:
            "Group smaller slices into one if big dataset",
          grouped_by: "Grouped by",
          grouped_value_empty: "Grouped value '{{ group }}' is empty",
          grouping: "Grouping",
          groups: "Groups",
          guide_to_dashboard_config: "Guide to dashboard configuration",
          half_year: "Biannually",
          has_been_granted_access_rights_to:
            "has been granted access rights to",
          header: "Voucher head",
          hidden_columns: "Hidden columns",
          hide_files: "Hide files",
          hide_guide: "Hide guide",
          how_to_distribute: "How to distribute",
          iban: "IBAN",
          import_pending_costs: "Import pending costs",
          import_transactions: "Import transactions",
          in_approval_flow: "Pending approval",
          inactive: "Inactive",
          inactive_substitute: "Inactive substitute",
          incoming_vat: "Incoming VAT",
          information: "Information",
          information_missing_to_complete_request_to_server:
            "Information missing to complete request to server",
          install_client: "Install Client",
          invalid_date_format: "Invalid date format",
          invalid_login_credentials: "Invalid login credentials",
          invoice_as: "Show invoice as",
          invoice_no: "Invoice number",
          invoice_number: "Invoice number",
          invoice_status: "Voucher status",
          is_a_member_of: "Is a member of",
          is_empty: "Is empty",
          is_not_empty: "Is not empty",
          item: "Item",
          its_just_403:
            "Server returned HTTP 403 error: 'Access to requested document' denied. Please check your credentials.",
          its_just_404:
            "Server returned HTTP 404 error: 'Requested document not found'. Please contact your systems administrator.",
          key: "Key",
          kontono: "Account number",
          language: "Language",
          languages: "Languages",
          last_opened: "Last opened",
          last_status_change: "Last status change",
          lastname: "Last name",
          latest_in_approval_timeline: "Newest in approval timeline",
          latest_release: "Latest release",
          less: "Less",
          less_than: "Less than",
          less_than_or_equal_to: "Less than or equal to",
          licence_type: "Licence type",
          licences: "Licences",
          license_id: "Licence ID",
          linear_scaling_on_y_axis: "Linear scaling on y-axis",
          link: "Link",
          linked: "Linked",
          list_of_generated_tables: "List of generated tables",
          load: "Load",
          load_agreement: "Load agreement",
          load_filter: "Load filter",
          load_more: "Load more",
          loading: "Loading...",
          loading_data: "Loading data",
          log_in: "Login",
          log_in_with_sso: "Log in with Single Sign-on",
          logarithmic_scaling_on_y_axis: "Logarithmic scaling on y-axis",
          login: "Login",
          login_with_another_account: "Log in with another account",
          login_with_msal: "Login with Microsoft credentials",
          "logout-options": "Logout-options",
          main: "Main",
          main_activity: "Main activity",
          main_criteria: "Main criteria",
          main_group: "Main group",
          make_chart: "Make chart",
          manage_substitutes: "Manage substitutes",
          manager: "Manager",
          manual: "User guide",
          mark_all_as_done: "Mark all as done",
          mark_all_as_read: "Mark all as read",
          max: "Max.",
          max_length_of_input_exceeded:
            "Maximum length of {{limit}} characters exceeded",
          me: "Me",
          media_type: "Media type",
          media_types: "Media types",
          media_types_included_in_the_agreement:
            "Media types included in the agreement",
          menu: "Menu",
          menu_item_information: "Menu item information",
          menu_rights_and_Dialog_design: "Menu rights and Dialog design",
          min: "Min.",
          miscellaneous: "Miscellaneous",
          module: "Module",
          modules: "Modules",
          monthly: "Monthly",
          monthly_sales: "Monthly sales",
          more: "More",
          move_widget: "Move widget",
          msal_accounts_mapping: "Microsoft accounts mapping",
          must_be_empty: "{{label}} must be empty",
          must_be_filled: "{{label}} must be filled out",
          my: "My",
          my_filters: "My filters",
          my_role: "My role",
          my_vouchers_pending_approval: "My vouchers pending approval",
          n_a: "N/A",
          name: "Name",
          new_key_for_demo: "New key for demo",
          new_name: "New name",
          next: "Next",
          no: "No",
          no_access: "No access",
          no_accounting_codes_selected: "No accounting codes selected",
          no_agreements_selected: "No agreements selected",
          no_cancel_reset: "No, cancel reset of dashboard",
          no_companies: "No companies",
          no_creditor_found: "No creditor found",
          no_data: "No data",
          no_description: "No description",
          no_documents_to_show_for_this_voucher:
            "No documents to show for this voucher.",
          no_favorites: "No favourites",
          no_favorites_yet: "No favourites yet",
          no_group_permissions: "No group permissions",
          no_items: "No items",
          no_menu_item_selected: "No menu item selected",
          no_notifications: "No notifications",
          no_notifications_selected: "No notifications selected",
          no_options: "No options",
          no_please_cancel_action: "No, cancel {{ action }}",
          no_products_found: "No products found",
          no_recent: "No recent",
          no_recents_yet: "No recents yet",
          no_recipients_selected: "No recipients selected",
          no_records: "No records",
          no_resource_found: "No resource found for your user.",
          no_results: "No results were found.",
          no_results_found: "No results found",
          no_rows_found: "No rows found.",
          no_settlement_groups_selected: "No settlement groups selected",
          no_sheets_selected: "No sheets selected",
          no_subscriptions: "No subscriptions",
          no_templates_selected: "No templates selected",
          no_user_permissions: "No user permissions",
          no_user_rights_granted: "No user rights granted",
          no_view_selected: "No view selected",
          no_voucher_found: "No voucher found",
          no_webservice_selected: "No web service selected",
          no_widget_selected: "No widget selected",
          not_approved_agent_entry: "Not approved user entry",
          not_equal_to: "Not equal to",
          not_included: "Not included",
          not_now: "Not now",
          not_selected: "Not selected",
          not_unique: "{{property}} is not unique",
          note_optional: "Note optional",
          note_required: "Note required",
          notifications: "Notifications",
          notifications_to_group: "Notifications to group",
          number: "Number",
          number_of_rows: "Count",
          numbers_only: "Numbers only",
          numeric_widget: "Numeric widget",
          of: "of",
          ok: "OK",
          older_versions_of_schilling_client:
            "Older versions of Schilling Client",
          only_approvers_may_add_entry: "Only approvers may add entry",
          oops_something_wrong: "Oops - something went wrong!",
          open_debtor: "Open debtor",
          open_in: "Open in",
          open_in_company: "Open in company",
          open_in_data_overview: "Open in Data Overview",
          open_in_schilling_client: "Open in Schilling Client",
          open_invoice: "Open invoice",
          open_source_software_used_in_schilling:
            "Open source software used in Schilling",
          open_the: "Open the",
          operator: "Operator",
          or: "Or",
          or_with_account: "Or with account",
          order_rights: "Order rights",
          other: "Other",
          overview: "Overview",
          overview_of_rights_per_company: "Overview of rights per company",
          overwrite_existing_filter: "Overwrite existing filter",
          owner: "Owner",
          package: "Package",
          package_type: "Package type",
          page: "Page",
          paid: "Paid",
          password: "Password",
          path: "Path",
          payment_date: "Payment date",
          payment_date_must_be_same_or_after_settlement_date:
            "Payment date must be the same as or after the settlement date",
          payment_reference: "Payment reference",
          pending: "Pending",
          pending_approval: "Pending approval",
          pending_approval_from: "Pending approval from",
          pending_for: "Pending for",
          percentage_value: "Percentage value",
          pie_chart: "Pie chart",
          please_note: "Please note",
          please_remember_to: "Please remember to",
          please_remember_to_setup_cron_jobs:
            "Please remember to setup cron jobs",
          please_specify_recipients: "Please specify recipients",
          popular: "Popular",
          post_as: "Post as",
          post_as_is_a_required_field: "Post as is a required field",
          postal_code: "Postal code",
          postal_town: "Postal town",
          posted_form: "Posted form",
          posting_entries_may_be_retrieved_from_purchase_order_no:
            "Voucher lines may be retrieved from purchase order number",
          preliminary_form: "Preliminary form",
          press_this_link_to_follow_up: "Click on link to follow up",
          preview: "Preview",
          preview_data: "Preview data",
          preview_groups: "Preview groups",
          previous: "Previous",
          previous_name: "Previous name",
          price_groups: "Price groups",
          private: "Private",
          process: "Process",
          "product(s)": "Product(s)",
          products: "Products",
          profit_sharing: "Profit sharing",
          profit_sharing_agreement: "Profit sharing agreement",
          profit_sharing_edit: "Edit profit sharing agreement",
          project: "Project",
          project_end: "Project end",
          project_is_a_required_field: "Project is a required field",
          project_name: "Project name",
          project_number: "Project number",
          project_status: "Project status",
          project_type: "Project type",
          projects: "Projects",
          projects_by_group: "Projects by group",
          projects_by_status: "Projects by status",
          projects_overview: "Projects overview",
          property: "Property",
          public: "Public",
          publication_date: "Publication date",
          publisher: "Publisher",
          publisher_share: "Publisher's share",
          publishers_share: "Publisher's share",
          purchase_order_number: "Purchase order number",
          quarterly: "Quarterly",
          quick_access: "Quick access",
          recalculate_cost_transactions: "Recalculate cost transactions",
          recalculate_sales_transactions: "Recalculate sales transactions",
          receive_notifications_in_access_point:
            "Receive notifications in Access Point",
          receive_notifications_in_mail_box:
            "Receive notifications in mail box",
          recent: "Recent",
          recipient_quantity: "Recipient/quantity",
          recipients: "Recipients",
          recipients_and_individual_shares: "Recipients and individual shares",
          recipients_payment_method: "Recipients payment method",
          recipients_share: "Recipient's share",
          registered: "Registered",
          registered_blocked: "Registered (blocked)",
          regno: "Regno",
          reimbursed: "Reimbursed",
          reject: "Reject",
          reject_all: "Reject for all",
          reject_for_me_and_subs: "Reject for me, {{subs}}",
          reject_for_substitutees: "Reject for {{subs}}",
          reject_present: "Reject",
          rejected: "Rejected",
          rejected_by: "Rejected by",
          rejected_by_approver: "Rejected by approver(s)",
          rejecting: "Rejecting",
          rejection_note_required: "Rejection note required*",
          remainder_of_x_number_of_smaller_y: "Remainder as one group",
          remove_from_favorites: "Remove from favourites",
          remove_widget: "Remove widget",
          report_form: "Report form",
          report_format: "Report format",
          required_field: "Required field",
          reset: "Reset",
          reset_dashboard: "Reset dashboard",
          reset_dashboard_explained: "Dashboard configuration guide",
          reset_table: "Reset table",
          resize_widget: "Resize widget",
          resource_is_not_specified: "Resource is not specified",
          restart: "Restart",
          results: "Results",
          retention_rate: "Retention rate",
          retention_rate_from_sales: "Retention rate from sales",
          return_date: "Return date",
          return_dates: "Return dates",
          return_to: "Return to",
          return_until: "Return until",
          returns: "Returns",
          rights: "Rights",
          route: "Route",
          row: "Row",
          row_plural: "Rows",
          rows: "Rows",
          royalty_settlement: "Royalty settlement",
          run_type: "Run type",
          sales: "Sales",
          sales_channels: "Sales channels",
          save: "Save",
          save_and_close: "Save and close",
          save_as: "Save as",
          save_as_new: "Save as new",
          save_chart: "Save chart",
          save_column_order: "Save column order",
          save_column_visibility: "Save column visibility",
          save_dashboard_config: "Save dashboard configuration",
          save_filter: "Save filter",
          save_the_group_by_column: "Save the group by column",
          save_the_selected_values: "Save the selected values",
          save_the_sort_by_column: "Save column sorting",
          save_widget: "Save widget",
          saved_search: "Saved search",
          scaling_function: "Scaling function",
          schedule_another: "Schedule another",
          schilling_client: "Schilling Client",
          schilling_legacy_client: "Schilling Legacy Client",
          schilling_package: "Schilling package",
          schilling_packages: "Schilling packages",
          schilling_web_service_documentation:
            "Schilling web service documentation",
          search: "Search",
          search_all: "Search all",
          search_by: "Search by",
          search_by_column: "Search by column",
          search_column: "Search column",
          search_columns: "Search columns",
          search_data: "Search data",
          search_for_agreement: "Search for agreement",
          search_in: "Search in",
          search_menu_items: "Search menu items",
          searching_view: "{{ view }}",
          select: "Select",
          select_all: "Select all",
          select_approver: "Select approver",
          select_chart_settings: "Select chart settings",
          select_column_to_search: "Select column",
          select_columns: "Select columns",
          select_companies: "Select companies",
          select_company: "Select company",
          select_data: "Select data",
          select_debtor: "Select debtor",
          select_filter: "Select filter",
          select_graph_height: "Select graph height",
          select_group: "Select group",
          select_list_size: "Select list size",
          select_media_types: "Select media types",
          select_notification: "Select notification",
          select_recipient: "Select recipient",
          select_retention_rate: "Select retention rate",
          select_rows: "Select rows",
          select_saved_search: "Select saved search",
          select_scaling_function: "Select scaling function",
          select_substitute: "Select substitute",
          select_user: "Select user",
          select_view_in_order_to_see_columns:
            "Select view in order to see columns",
          select_view_to_search: "Select view",
          select_widget_theme: "Select widget theme",
          select_widget_type: "Select widget type",
          selected: "Selected",
          selected_company_does_not_have_PIA_module:
            "The selected company does not have the Supplier Invoice Approval module",
          selected_company_does_not_have_supported_modules:
            "The selected company does not have the supporting modules",
          send_to_support: "Send to support",
          send_to_www: "Send to www",
          sequence: "Sequence",
          server: "Server",
          set_column_visibility: "Set column visibility",
          set_fontsize_here: "Set fontsize here",
          set_rights_for_groups: "Set rights for groups",
          set_rights_for_users: "Set rights for users",
          settlement: "Settlement",
          settlement_and_payment_dates: "Settlement and payment dates",
          settlement_date: "Settlement date",
          settlement_date_must_be_same_or_after_max_publishing_date:
            "Settlement date must be the same as or after the maximum publication date",
          settlement_group: "Settlement group",
          settlement_groups: "Settlement groups",
          settlement_list: "Settlement list",
          settlement_period: "Settlement period",
          settlement_run: "Settlement run",
          settlement_run_created: "Settlement run created",
          settlement_run_creation_failed: "Settlement run creation failed",
          settlement_run_progress: "Settlement run progress",
          settlement_runs: "Settlement runs",
          settlement_type: "Settlement type",
          settlements: "Settlements",
          shares: "Shares",
          sheets: "Sheets",
          should_not_be_longer_than:
            "{{property}} should not be longer than {{count}} characters",
          should_not_be_longer_than_plural:
            "{{property}} should not be longer than {{count}} characters",
          should_not_include_empty_spaces:
            "{{property}} should not include empty spaces",
          show_active: "Show active",
          show_all: "Show all",
          show_all_notifications: "Show all notifications",
          show_chart: "Show chart",
          show_data: "Show data",
          show_grouped_value_as: "Show grouped value as",
          show_less: "Show less",
          show_log: "Show log",
          show_more: "Show more",
          signout: "Log out",
          signout_including_msal: "Log out of all under Microsoft credentials",
          simple: "Simple",
          socsecnumber: "Social security number",
          software_name: "Software name",
          sold: "Sold",
          solid: "Solid",
          sort: "Sort",
          sort_by: "Sort by",
          sorting: "Sorting",
          specify_individual_shares: "Specify individual shares",
          sso_login_failed: "SSO login failed",
          stack_chart: "Stack chart",
          stakeholder_name: "Stakeholder name",
          start_date: "Start date",
          status: "Status",
          step: "Step {{step}} of {{numberOfSteps}}",
          step_1: "Step 1",
          step_1_error: "Step 1 error",
          step_2: "Step 2",
          step_3: "Step 3",
          stop: "Stop",
          street_number: "Street number",
          sub_criteria: "Sub-criteria",
          subscriptions: "Subscriptions",
          substitute: "Substitute",
          substitutes: "Substitutes",
          sum: "Sum",
          sum_of_recipients_share_is_not_100:
            "Sum of recipients' share is not 100",
          summary: "Summary",
          supplier_invoice_approval: "Supplier Invoice Approval",
          supplier_invoice_number: "Supplier invoice number",
          swift: "SWIFT",
          swift_code: "SWIFT code",
          systabs: "Systabs",
          system: "System",
          system_error: "System error - please try again later",
          system_name_and_payment_information:
            "System name and payment information",
          system_params: "System params",
          system_widget: "System widget",
          systexts: "Systexts",
          table: "Table",
          table_config: "Table configuration",
          territory: "Territory",
          text: "Text",
          text_search_across_all_columns: "Text search across all columns",
          the_same_cost_type_error:
            "The same cost type must have different transaction types and media types",
          the_share_may_not_be_zero_on_every_step:
            "The share may not be zero on every step",
          theme: "Theme",
          there_are_results_in_the_classic_menu:
            "There is {{count}} result in the classic menu",
          there_are_results_in_the_classic_menu_plural:
            "There are {{count}} results in the classic menu",
          this_is_a_read_only_company: "This is a read only company",
          company_has_been_changed: "Company has been changed",
          title: "Title",
          tlog: "Change logs",
          to: "To",
          to_change_the_column_order_just_drag_them_to_your_desired_location:
            "Change the column order by dragging them to your desired location",
          to_confirm: "to confirm",
          to_date: "To",
          to_duedate: "To due date",
          too_many_requests: "Too many requests",
          total: "Total",
          total_entries: "Total entries",
          total_entries_main: "Total entries for the main criteria",
          total_entries_sub: "Total entries for the sub-cirteria",
          total_groups: "Total groups",
          total_results: "Total results",
          total_rows: "Total rows",
          transfer_transactions_for_editing:
            "Transfer transactions for editing",
          try_again: "Try again",
          type: "Type",
          unclassified: "Unclassified",
          undecided: "Undecided",
          undefined: "Undefined",
          unknown_error_occured: "An unknown error occured",
          unset: "undetermined",
          unspecified: "Unspecified",
          untitled: "Voucher number missing",
          untitled_filter: "Untitled filter",
          up_to: "Up to",
          up_to_including: "Up to including",
          upcoming: "Upcoming",
          update: "Update",
          update_substitute: "Update substitute",
          update_to: "Update to",
          updated: "Updated",
          used_for: "Used for",
          user: "User",
          user_rights: "User rights",
          user_rights_for_companies: "User rights for companies",
          user_rights_for_menu_items: "User rights for menu items",
          user_rights_for_rest: "User rights for REST web services",
          user_rights_for_rest_web_services:
            "User rights for REST web services",
          user_rights_for_views: "User rights for views",
          user_rights_for_widget: "User rights for widget",
          user_rights_for_widgets: "User rights for widgets",
          username: "User",
          users: "Users",
          utilized_before: "Utilised before",
          valid_from: "Valid from",
          valid_to: "Valid to",
          value: "Value",
          values: "Values",
          vat: "VAT",
          vatregno: "VAT registration number",
          verification_code: "Verification code",
          version: "Version",
          view: "View",
          view_details: "View details",
          view_does_not_have_saved_searches:
            "View does not have any saved searches",
          view_files: "View files",
          view_retention_codes: "View retention codes",
          views: "Views",
          visibility: "Visibility",
          voucher: "Voucher",
          voucher_date: "Voucher date",
          voucher_details: "Voucher details",
          voucher_entries_in_purchase_order:
            "Voucher entries in purchase order",
          voucher_has_been_reimbursed: "Voucher has been reimbursed",
          voucher_no: "Voucher number",
          voucher_not_ready_for_handling_by_approvers:
            "Voucher not ready for handling by approvers",
          voucher_past_approval_flow: "Voucher is past approval flow",
          voucher_text: "Voucher text",
          vouchers: "Vouchers",
          vouchers_in_my_department_pending_processing:
            "Vouchers in my department pending processing",
          warning: "Warning",
          welcome: "Welcome",
          welcome_to_schilling: "Welcome to Schilling",
          when_you_open_programs_from_the_menu_they_will_appear_here:
            "When you open programs from the menu they will appear here",
          which_company_do_you_want_to_see_permissions_for:
            "Which company do you want to see permissions for?",
          who_do_you_want_to_give_rights_to:
            "Who do you want to give rights to?",
          widget: "Widget",
          widget_component_is_missing_or_invalid:
            "Widget component is missing or invalid",
          widget_creation_failed: "Could not create widget",
          widget_data: "Widget data",
          widget_data_deleted_or_made_private_by_owner:
            "Widget data deleted or made private by owner",
          widget_settings: "Widget settings",
          widget_successfully_created: "Widget successfully created",
          widget_type: "Widget type",
          widgets: "Widgets",
          widgets_overview: "Widget overview",
          withhold: "Withhold",
          work_id: "Work ID",
          "x-axis": "X-axis",
          "y-axis": "Y-axis",
          yes_go_ahead_and_reset_dashboard: "Yes, go ahead and reset dashboard",
          yes_please_do_action: "Yes please {{ action }} ",
          yes_reset_dashboard: "Yes, reset dashboard",
          you_already_approved_voucher: "You have already responded",
          you_approve_on_behalf_of:
            "You are a substitute and therefore {{action}} on behalf of",
          you_approved_this_voucher: "You approved this voucher",
          you_are_about_to_assign_a_package_to_customer:
            "You are about to assign a package to customer",
          you_are_about_to_permanently_delete_agreement:
            "You are about to permanently delete agreement",
          you_are_about_to_permanently_delete_package:
            "You are about to permanently delete package",
          you_are_about_to_permanently_delete_user_mapping:
            "You are about to permanently delete user mapping",
          you_are_about_to_permanently_delete_widget:
            "You are about to permanently delete the widget",
          you_are_about_to_permanently_set_author_portal:
            "You are about to permanently set author portal",
          you_are_editing_rights_for: "You are editing rights for",
          you_can_hide_or_show_columns_by_clicking_the_checkbox:
            "Hide or show columns by clicking the checkbox",
          you_can_select_a_menu_item_by_clicking_the_edit_icon_in_the_table:
            "You can select a menu item by clicking the edit icon in the table",
          you_can_select_a_view_by_clicking_the_edit_icon_in_the_table:
            "You can select a view by clicking the edit icon in the table",
          you_can_select_a_webservice_by_clicking_the_edit_icon_in_the_table:
            "You can select a web service by clicking the edit icon in the table",
          you_can_select_a_widget_by_clicking_the_edit_icon_in_the_table:
            "You can select a widget by clicking the edit icon in the table",
          you_need_admin_privileges_in_order_to_edit_user_rights:
            "You need admin privileges in order to edit user rights",
          you_need_admin_privileges_in_order_to_setup_author_portal:
            "You need admin privileges in order to setup author portal",
          you_need_admin_privileges_in_order_to_setup_msal_accounts:
            "You need admin privileges in order to setup Microsoft login",
          you_need_admin_privileges_in_order_to_setup_packages:
            "You need admin privileges in order to setup packages",
          you_rejected_this_voucher: "You rejected this voucher",
          your_device_is_not_supported: "Your device is not supported",
        },
      },
    },
    language: "en",
    languages: ["en"],
    resolvedLanguage: "en",
  },
  tReady: true,
};

export const tableExampleData = {
  headers,
  data,
  config,
};
